config/routes.rb
KingServer::Application.routes.draw do
  
  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api do
    namespace :v1  do
      resources :tokens, only: [:create, :destroy]
      resources :locations, only: [:create]
      post '/check_in' => 'check_ins#check_in', format: :json
      post '/user_info' => 'users#my_info', format: :json
      post '/room_info' => 'rooms#get_room_info', format: :json
      post '/location_info' => 'locations#get_location_info', format: :json
      post '/hidden_check' => 'check_ins#hidden_check_in', format: :json
      post '/hidden_locations' => 'locations#get_close_locations', format: :json
    end
  end

  scope '(:locale)' do
    resources :hidden_locations
    resources :buildings
    resources :study_courses
    resources :rooms
    devise_for :users
    resources :users

    get '/admin' => 'study_courses#admin_home', as: 'admin'
    get '/rooms/:id/get_image' => 'rooms#get_image', as: 'get_image'
    get '/room_info/:building_id/:number' => 'study_courses#room_chart'
    get '/statistics' => 'study_courses#statistics', as: 'statistics'

    root to: 'study_courses#home'

  end

end

app/models/hidden_location.rb
class HiddenLocation < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :name, :points, :hint
  reverse_geocoded_by :latitude, :longitude
  validates_presence_of :latitude, :longitude, :name, :points, :hint
  has_many :checked_locations
  has_many :users, through: :checked_locations

  def as_json(options)
    super(except: [:created_at, :updated_at])
  end
end

app/controllers/hidden_locations_controller.rb
class HiddenLocationsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /hidden_locations
  # GET /hidden_locations.json
  def index
    @hidden_locations = HiddenLocation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hidden_locations }
    end
  end

  # GET /hidden_locations/1
  # GET /hidden_locations/1.json
  def show
    @hidden_location = HiddenLocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hidden_location }
    end
  end

  # GET /hidden_locations/new
  # GET /hidden_locations/new.json
  def new
    @hidden_location = HiddenLocation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hidden_location }
    end
  end

  # GET /hidden_locations/1/edit
  def edit
    @hidden_location = HiddenLocation.find(params[:id])
  end

  # POST /hidden_locations
  # POST /hidden_locations.json
  def create
    @hidden_location = HiddenLocation.new(params[:hidden_location])

    respond_to do |format|
      if @hidden_location.save
        format.html { redirect_to @hidden_location, notice: 'Hidden location was successfully created.' }
        format.json { render json: @hidden_location, status: :created, location: @hidden_location }
      else
        format.html { render action: "new" }
        format.json { render json: @hidden_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hidden_locations/1
  # PUT /hidden_locations/1.json
  def update
    @hidden_location = HiddenLocation.find(params[:id])

    respond_to do |format|
      if @hidden_location.update_attributes(params[:hidden_location])
        format.html { redirect_to @hidden_location, notice: 'Hidden location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hidden_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hidden_locations/1
  # DELETE /hidden_locations/1.json
  def destroy
    @hidden_location = HiddenLocation.find(params[:id])
    @hidden_location.destroy

    respond_to do |format|
      format.html { redirect_to hidden_locations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hidden_locations_helper.rb
module HiddenLocationsHelper
end

app/views/hidden_locations/_form.html.haml
= form_for @hidden_location, html: {class: "form-horizontal"} do |f|
  - if @hidden_location.errors.any?
    .container
      .alert.alert-danger
        %h2= "#{pluralize(@hidden_location.errors.count, "error")} prohibited this hidden_location from being saved:"
        %ul
          - @hidden_location.errors.full_messages.each do |msg|
            %li= msg

  .control-group
    = f.label :name, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-flag"}
        = f.text_field :name
  .control-group
    = f.label :latitude, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-bolt"}
        = f.text_field :latitude
  .control-group
    = f.label :longitude, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-bolt"}
        = f.text_field :longitude
  .control-group
    = f.label :hint, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-tags"}
        = f.text_field :hint
  .control-group
    = f.label :points, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-globe"}
        = f.text_field :points
  .control-group
    .controls
      = f.submit t("global.save"), class: "btn btn-success"

app/views/hidden_locations/edit.html.haml
%h1 Editing hidden_location

= render 'form'

= link_to 'Show', @hidden_location
\|
= link_to 'Back', hidden_locations_path

app/views/hidden_locations/index.html.haml
%legend Hidden Locations

%table{class: 'table table-hover'}
  %thead
    %tr
      %th Name
      %th Latitude
      %th Longitude
      %th Hint
      %th Points
      %th

    - @hidden_locations.each do |hidden_location|
      %tr
        %td= hidden_location.name
        %td= hidden_location.latitude
        %td= hidden_location.longitude
        %td= hidden_location.hint
        %td= hidden_location.points
        %td= link_to 'Show', hidden_location, class: 'btn btn-small'
        %td= link_to 'Edit', edit_hidden_location_path(hidden_location), class: 'btn btn-small btn-warning'
        %td= link_to 'Destroy', hidden_location, class: 'btn btn-small btn-danger', :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Hidden location', new_hidden_location_path, class: 'btn btn-inverse'

app/views/hidden_locations/new.html.haml
%legend New hidden location

= render 'form'

= link_to 'Back', hidden_locations_path, class: 'btn btn-inverse'

app/views/hidden_locations/show.html.haml
%legend Showing location

%p
  %b Name:
  = @hidden_location.name
%p
  %b Latitude:
  = @hidden_location.latitude
%p
  %b Longitude:
  = @hidden_location.longitude
%p
  %b Hint:
  = @hidden_location.hint
%p
  %b Longitude:
  = @hidden_location.points

= link_to 'Edit', edit_hidden_location_path(@hidden_location), class: 'btn btn-warning'
= link_to 'Back', hidden_locations_path, class: 'btn btn-inverse'