config/routes.rb
KingServer::Application.routes.draw do
  
  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api do
    namespace :v1  do
      resources :tokens, only: [:create, :destroy]
      resources :locations, only: [:create]
      post '/check_in' => 'check_ins#check_in', format: :json
      post '/user_info' => 'users#my_info', format: :json
      post '/room_info' => 'rooms#get_room_info', format: :json
      post '/location_info' => 'locations#get_location_info', format: :json
      post '/hidden_check' => 'check_ins#hidden_check_in', format: :json
      post '/hidden_locations' => 'locations#get_close_locations', format: :json
    end
  end

  scope '(:locale)' do
    resources :hidden_locations
    resources :buildings
    resources :study_courses
    resources :rooms
    devise_for :users
    resources :users

    get '/admin' => 'study_courses#admin_home', as: 'admin'
    get '/rooms/:id/get_image' => 'rooms#get_image', as: 'get_image'
    get '/room_info/:building_id/:number' => 'study_courses#room_chart'
    get '/statistics' => 'study_courses#statistics', as: 'statistics'

    root to: 'study_courses#home'

  end

end

app/models/building.rb
class Building < ActiveRecord::Base
  include ApplicationHelper
  attr_accessible :latitude, :longitude, :name
  has_many :rooms, dependent: :destroy

  def data_for_graph
    result = "{ y: #{self.checked_users}, color: colors[#{self.id - 1}], drilldown: { name: '#{self.name}',
                categories: [#{self.rooms.ordered.collect{|r| r.human}.join ', '}], data: [#{parse_rooms(self.rooms.ordered)}],
                color: colors[#{self.id - 1}]} }"
  end

  def self.print_all
    Building.all.collect{|b| "'#{b.name}'"}.join ', '
  end

  def self.print_data
    Building.all.collect{|b| b.data_for_graph}.join ', '
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buildings }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    @building = Building.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/new
  # GET /buildings/new.json
  def new
    @building = Building.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/1/edit
  def edit
    @building = Building.find(params[:id])
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(params[:building])

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: "new" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.json
  def update
    @building = Building.find(params[:id])

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.haml
= form_for @building, html: {class: "form-horizontal"} do |f|
  - if @building.errors.any?
    .container
      .alert.alert-danger
        %h2= "#{pluralize(@building.errors.count, "error")} prohibited this building from being saved:"
        %ul
          - @building.errors.full_messages.each do |msg|
            %li= msg

  .control-group
    = f.label :name, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-arrow-right"}
        = f.text_field :name
  .control-group
    = f.label :latitude, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-arrow-right"}
        = f.text_field :latitude
  .control-group
    = f.label :longitude, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-arrow-right"}
        = f.text_field :longitude
  .control-group
    .controls
      = f.submit t('global.save'), class: 'btn btn-success'

app/views/buildings/edit.html.haml
%h1 Editing building

= render 'form'

= link_to 'Show', @building
\|
= link_to 'Back', buildings_path

app/views/buildings/index.html.haml
%legend Buildings

%table{class: 'table table-hover'}
  %thead
    %tr
      %th Name
      %th Latitude
      %th Longitude
      %th
      %th
      %th

    - @buildings.each do |building|
      %tr
        %td= building.name
        %td= building.latitude
        %td= building.longitude
        %td= link_to 'Show', building, class: 'btn btn-small'
        %td= link_to 'Edit', edit_building_path(building), class: 'btn btn-warning btn-small'
        %td= link_to 'Destroy', building, class: 'btn btn-danger btn-small', :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Building', new_building_path, class: 'btn btn-inverse'

app/views/buildings/new.html.haml
%legend New building

= render 'form'

= link_to 'Back', buildings_path, class: 'btn btn-inverse'

app/views/buildings/show.html.haml
%p
  %b Name:
  = @building.name
%p
  %b Latitude:
  = @building.latitude
%p
  %b Longitude:
  = @building.longitude

= link_to 'Edit', edit_building_path(@building), class: 'btn btn-warning'
= link_to 'Back', buildings_path, class: 'btn btn-inverse'