config/routes.rb
KingServer::Application.routes.draw do
  
  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api do
    namespace :v1  do
      resources :tokens, only: [:create, :destroy]
      resources :locations, only: [:create]
      post '/check_in' => 'check_ins#check_in', format: :json
      post '/user_info' => 'users#my_info', format: :json
      post '/room_info' => 'rooms#get_room_info', format: :json
      post '/location_info' => 'locations#get_location_info', format: :json
      post '/hidden_check' => 'check_ins#hidden_check_in', format: :json
      post '/hidden_locations' => 'locations#get_close_locations', format: :json
    end
  end

  scope '(:locale)' do
    resources :hidden_locations
    resources :buildings
    resources :study_courses
    resources :rooms
    devise_for :users
    resources :users

    get '/admin' => 'study_courses#admin_home', as: 'admin'
    get '/rooms/:id/get_image' => 'rooms#get_image', as: 'get_image'
    get '/room_info/:building_id/:number' => 'study_courses#room_chart'
    get '/statistics' => 'study_courses#statistics', as: 'statistics'

    root to: 'study_courses#home'

  end

end

app/controllers/study_courses_controller.rb
class StudyCoursesController < ApplicationController
  before_filter :authenticate_user!, except: :home
  load_and_authorize_resource

  def statistics
    respond_to do |format|
      format.html
    end
  end

  def home
    respond_to do |format|
      format.html
    end
  end

  def room_chart
    @room = Room.where(building_id: params[:building_id], number: params[:number])
    if @room.empty?
      redirect_to root_url and return
    end
    respond_to do |format|
      format.html
    end
  end

  def admin_home
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  # GET /study_courses
  # GET /study_courses.json
  def index
    @study_courses = StudyCourse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @study_courses }
    end
  end

  # GET /study_courses/1
  # GET /study_courses/1.json
  def show
    @study_course = StudyCourse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @study_course }
    end
  end

  # GET /study_courses/new
  # GET /study_courses/new.json
  def new
    @study_course = StudyCourse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @study_course }
    end
  end

  # GET /study_courses/1/edit
  def edit
    @study_course = StudyCourse.find(params[:id])
  end

  # POST /study_courses
  # POST /study_courses.json
  def create
    @study_course = StudyCourse.new(params[:study_course])

    respond_to do |format|
      if @study_course.save
        format.html { redirect_to @study_course, notice: 'Study course was successfully created.' }
        format.json { render json: @study_course, status: :created, location: @study_course }
      else
        format.html { render action: "new" }
        format.json { render json: @study_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /study_courses/1
  # PUT /study_courses/1.json
  def update
    @study_course = StudyCourse.find(params[:id])

    respond_to do |format|
      if @study_course.update_attributes(params[:study_course])
        format.html { redirect_to @study_course, notice: 'Study course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @study_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study_courses/1
  # DELETE /study_courses/1.json
  def destroy
    @study_course = StudyCourse.find(params[:id])
    @study_course.destroy

    respond_to do |format|
      format.html { redirect_to study_courses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/study_courses_helper.rb
module StudyCoursesHelper
end

app/views/study_courses/_form.html.haml
= form_for @study_course, html: {class: "form-horizontal"} do |f|
  - if @study_course.errors.any?
    .container
      .alert.alert-danger
        %h2= "#{pluralize(@study_course.errors.count, "error")} prohibited this study_course from being saved:"
        %ul
          - @study_course.errors.full_messages.each do |msg|
            %li= msg

  .control-group
    .controls
      = f.label :name
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-arrow-right"}
        = f.text_field :name
  .control-group
    .controls
      = f.submit 'Save', class: 'btn'

app/views/study_courses/admin_home.html.haml
%legend= t('admin.title')

= link_to 'See all users', users_path, class: 'btn btn-inverse'
= link_to 'See all rooms', rooms_path, class: 'btn'
= link_to 'See all hidden locations', hidden_locations_path, class: 'btn btn-primary'
= link_to 'See all buildings', buildings_path, class: 'btn btn-warning'

app/views/study_courses/edit.html.haml
%h1 Editing study_course

= render 'form'

= link_to 'Show', @study_course
\|
= link_to 'Back', study_courses_path

app/views/study_courses/home.html.haml
%legend A different kind of geo-location Game

.span12
  .span4.offset1
    %img{:alt => 'Scan to download the game', :height => "150", :src => "img/download_apk.png"}/
  .span4.offset1
    %br/
    %h2 King of HFT
    %h3 Get the Game
    %p
      Get the Android App now. As download
      %a{:href => "/KingApp.apk"} here
      in the Play Store or as direct download via QR-Code.
  .span4.offset1
    %br/
    %h3 Game Instructions
    %ul
      %li The point of the game is to check into as many rooms as possible
      %li All you need to do is find a room in the HFT with a QR Code on the door
      %li Scan the QR Code
      %li Have your friends check into the room as well
      %li Once enough of the students from the same study course check in the room belongs to them
      %li Once the room is yours, take over the building!
      %li Engage your friends outside of the HFT by creating Hidden Locations anywhere on the city and give the points for finding them.
    %img{:alt => "", :height => "150", :src => "img/play.jpg"}/

    -#%h3 Simple game play
    -#%p
    -#  Big pleasure. Join the community and play with friends and other students. How to play? Simple! Just follow
    -#  %a{:href => "linkToInstuctions"}
    -#    the instructions
  .span4.offset1
    %br/
    %h3 Scoreboard
    %img{:alt => "", :height => "150", :src => "img/logo.png"}/
    %h3 The best of the best
    %p
      just take a look.
      = link_to 'Show me!', statistics_path

app/views/study_courses/index.html.haml
%legend= t('study_courses.title')

%p= t('study_courses.description')

%table{class: 'table table-hover'}
  %thead
    %tr
      %th Name

  - @study_courses.each do |study_course|
    %tr
      %td= study_course.name
      %td= link_to 'Show', study_course, class: 'btn btn-small'
      %td= link_to 'Edit', edit_study_course_path(study_course), class: 'btn btn-small btn-warning'
      %td= link_to 'Destroy', study_course, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-small btn-danger'

%br
-if can? :manage, StudyCourse
  = link_to t('study_courses.new'), new_study_course_path, class: 'btn btn-primary'

app/views/study_courses/new.html.haml
%legend= t('study_courses.title')

= render 'form'

= link_to 'Back', study_courses_path, class: 'btn btn-inverse'

app/views/study_courses/room_chart.html.haml
%legend Statistics for #{@room.first.extra_human}
#myCont
:javascript
  $('#myCont').highcharts({
        chart: {
          type: 'column'
        },
        title: {
          text: 'Statistics of checked in users'
        },
        xAxis: {
          categories: ['Studies']
        },
        yAxis: {
          min: 0,
          title: {
            text: "Number of users in room #{@room.first.extra_human}"
          }
        },
        plotOptions: {
            column: {
              dataLabels: {
                  enabled: true,
                  //color: colors[0],
                  style: {
                      fontWeight: 'bold'
                  },
                  formatter: function() {
                      return this.y;
                  }
              }
            }
        },
        series: [#{StudyCourse.print_graph(@room.first)}]
      });

app/views/study_courses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @study_course.name

= link_to 'Edit', edit_study_course_path(@study_course)
\|
= link_to 'Back', study_courses_path

app/views/study_courses/statistics.html.haml
%legend Current Game Statistics
.container
  #timeContainer
    .span4
    .span4
      %h5{style: 'text-align: center;'} Time left in current game
      %ul#timer
    .span4
  :javascript
    jQuery(document).ready(function($) {
        CreateTimer("timer", {
            year: 2013,
            month: 6,
            day: 15
        });
    });

%ul.nav.nav-tabs#statsTab
  %li.active
    %a{href: '#upb'} Users per building
  %li
    %a{href: '#sc'} Most active Study Courses
  -#%li
  -#  %a{href: '#wn'} Who's winning?

.tab-content
  .tab-pane.active#upb
    #myCont
  .tab-pane#sc
    #myCont2
  -#.tab-pane#wn
  -#  #pieChart

:javascript
  function xinspect(obj){
      var str = "";
      for(var k in obj)
          if (obj.hasOwnProperty(k)) //omit this test if you want to see built-in properties
              str += k + " = " + obj[k] + "\n";
      alert(str);
  }
  var colors = Highcharts.getOptions().colors,
    categories = [#{Building.print_all}],
    name = 'Building names',
    data = [#{Building.print_data}];
    function setChart(name, categories, data, color, s_title, s_subtitle) {
        chart.xAxis[0].update({max: 20})
        chart.xAxis[0].setCategories(categories, false);
        chart.setTitle({text: s_title}, {text: s_subtitle});
        chart.series[0].remove(false);
        chart.addSeries({
            name: name,
            data: data,
            color: color || 'white'
        }, false);
        chart.redraw();
    }

    var chart = $('#myCont').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Number of check-ins per building'
        },
        subtitle: {
            text: 'Click the columns to view the rooms in each building.'
        },
        xAxis: {
            categories: categories
        },
        scrollbar: {
            enabled: true
        },
        yAxis: {
            title: {
                text: 'Total number of check-ins'
            }
        },
        plotOptions: {
            column: {
                cursor: 'pointer',
                point: {
                  events: {
                    click: function() {
                      var drilldown = this.drilldown;
                      if (drilldown) { // drill down
                          setChart(drilldown.name, drilldown.categories, drilldown.data, drilldown.color,
                                   'Users checked in per building', 'Click the columns to view each room');
                      } else { // go to room info
                          window.location.href = '/en/room_info/'+this.category
                          //alert(this.category);
                          //setChart(name, categories, data);
                      }
                    }
                  }
                },
                dataLabels: {
                    enabled: true,
                    color: colors[0],
                    style: {
                        fontWeight: 'bold'
                    },
                    formatter: function() {
                        return this.y;
                    }
                }
            }
        },
        tooltip: {
            formatter: function() {
                var point = this.point,
                    s = this.x +':<b>'+ this.y +' users checked in</b><br/>';
                if (point.drilldown) {
                    s += 'Click to view '+ point.category +' rooms';
                } else {
                    s += 'Click to view room statistics';
                }
                return s;
            }
        },
        series: [{
            name: name,
            data: data,
            color: 'white'
        }],
        exporting: {
            //enabled: true,
            buttons: {
                'myButton': {
                    _id: 'myButton',
                    symbol: 'diamond',
                    x: 2,
                    symbolFill: '#B5C9DF',
                    hoverSymbolFill: '#779ABF',
                    onclick: function() {
                        alert('click!')
                    }
                }
            }
        }
    })
    .highcharts(); // return chart
    jQuery(document).ready(function($) {
       $('#statsTab').find('a').click(function (e) {
          e.preventDefault();
          $(this).tab('show');
          var server = $(this).prop('href').split('#');
          if (server[1] == 'sc') {
            $('#myCont2').highcharts({
                chart: {
                  type: 'column'
                },
                title: {
                  text: 'Most active study courses'
                },
                xAxis: {
                  categories: ['Study Courses']
                },
                yAxis: {
                  min: 0,
                  title: {
                    text: 'Number of check-ins per Study Course'
                  }
                },
                plotOptions: {
                    column: {
                      dataLabels: {
                          enabled: true,
                          //color: colors[0],
                          style: {
                              fontWeight: 'bold'
                          },
                          formatter: function() {
                              return this.y;
                          }
                      }
                    }
                },
                series: [#{StudyCourse.print_sc_graph}]
              });
          } else if (server[1] == 'upb') {
            chart.redraw();
          }
       });
    });