config/routes.rb
KingServer::Application.routes.draw do
  
  constraint = lambda { |request| request.env['warden'].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api do
    namespace :v1  do
      resources :tokens, only: [:create, :destroy]
      resources :locations, only: [:create]
      post '/check_in' => 'check_ins#check_in', format: :json
      post '/user_info' => 'users#my_info', format: :json
      post '/room_info' => 'rooms#get_room_info', format: :json
      post '/location_info' => 'locations#get_location_info', format: :json
      post '/hidden_check' => 'check_ins#hidden_check_in', format: :json
      post '/hidden_locations' => 'locations#get_close_locations', format: :json
    end
  end

  scope '(:locale)' do
    resources :hidden_locations
    resources :buildings
    resources :study_courses
    resources :rooms
    devise_for :users
    resources :users

    get '/admin' => 'study_courses#admin_home', as: 'admin'
    get '/rooms/:id/get_image' => 'rooms#get_image', as: 'get_image'
    get '/room_info/:building_id/:number' => 'study_courses#room_chart'
    get '/statistics' => 'study_courses#statistics', as: 'statistics'

    root to: 'study_courses#home'

  end

end

app/models/room.rb
# encoding: UTF-8
require 'digest/sha1'
require 'rqrcode_png'

class Room < ActiveRecord::Base
  attr_accessible :building_id, :claimed, :claimed_by, :number, :qr_code_path
  validates_presence_of :building_id, :number
  has_many :locations, dependent: :destroy
  has_many :users, through: :locations
  belongs_to :building
  scope :ordered, order('number asc')
  scope :by_building, order('building_id asc')

  before_save do
    self.id_hash = Digest::SHA1.hexdigest("#{self.created_at}#{self.number}#{self.building_id}")
    self.qr_code_path = "#{self.building_id}_#{self.number}.png"
    qr = RQRCode::QRCode.new(self.id_hash, size: 4, level: :m)
    png = qr.to_img
    self.qr_data = png.resize(400, 400).to_s
  end

  def as_json(options)
    super(except: [:qr_code_path, :created_at, :updated_at, :id, :qr_data])
  end

  def set_claimed_label
    status = {false => 'important', true => 'success'}
    status[self.claimed]
  end

  def claimed_status
    if self.claimed
      '✔'
    else
      '✘'
    end
  end

  def human
    "'#{self.building_id}/#{self.number}'"
  end

  def extra_human
    "#{self.building_id}/#{self.number}"
  end

  def self.print_all
    Room.ordered.collect{|r| r.human}.join ', '
  end

  def print_data
    result = '['
    StudyCourse.all.each do |s|
      num = 0
      self.users.each do |u|
        if u.study_course == s
          num += 1
        end
      end
      result += "#{num}, "
    end
    result.chomp!(', ')
    result += ']'
  end
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < ApplicationController
  before_filter :authenticate_user!
  skip_authorization_check

  respond_to :json

  def get_room_info
    begin
      room = Room.find_by_id_hash(params[:room_hash])
      unless room.nil?
        studies = []
        users = room.users
        users.each do |user|
          studies << user.studies
        end

        stats = Hash.new(0)
        studies.each do |st|
          stats[st] += 1
        end

        render status: 200, json: { users: users.size, stats: stats, room: room }
        return
      end
      render status: 500, json: { message: 'Record not found' }

    rescue ActiveRecord::RecordNotFound
      render status: 500, json: { message: 'Record not found' }
      return
    end
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.by_building.ordered

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end

  def get_image
    @photo = Room.find(params[:id])
    send_data(@photo.qr_data, :type => 'image/png', :filename => "#{@photo.qr_code_path}", :disposition => 'inline')
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.haml
= form_for @room, html: {class: "form-horizontal"} do |f|
  - if @room.errors.any?
    .container
      .alert.alert-danger
        %h2= "#{pluralize(@room.errors.count, "error")} prohibited this room from being saved:"
        %ul
          - @room.errors.full_messages.each do |msg|
            %li= msg

  .control-group
    = f.label :building_id, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-user"}
        = f.select :building_id, Hash[Building.all.map{|b| [b.name, b.id]}]
  .control-group
    = f.label :number, class: "control-label"
    .controls
      .input-prepend
        %span{class: "add-on"}
          %i{class: "icon-user"}
        = f.text_field :number
  .control-group
    .controls
      = f.submit t("global.save"), class: "btn btn-success"

app/views/rooms/edit.html.haml
%legend Editing room

= render 'form'

= link_to 'Show', @room, class: 'btn'
= link_to 'Back', rooms_path, class: 'btn btn-inverse'

app/views/rooms/index.html.haml
%legend Listing rooms

%table{class: 'table table-hover'}
  %thead
    %tr
      %th Building
      %th Number
      %th Claimed
      %th Claimed by

  - @rooms.each do |room|
    %tr
      %td= room.building.name unless room.building.nil?
      %td= room.number
      %td
        %span{class: "label label-#{room.set_claimed_label}"}
          = room.claimed_status
      %td= room.claimed_by
      %td= link_to 'Show', room, class: 'btn btn-small'
      %td= link_to 'Edit', edit_room_path(room), class: 'btn btn-small btn-warning'
      %td= link_to 'Destroy', room, method: :delete, data: { :confirm => 'Are you sure?' }, class: 'btn btn-small btn-danger'

%br

= link_to 'New Room', new_room_path, class: 'btn btn-primary'

app/views/rooms/new.html.haml
%legend New room

= render 'form'

= link_to 'Back', rooms_path, class: 'btn btn-inverse'

app/views/rooms/show.html.haml
%legend Showing stats for room #{@room.building_id}/#{@room.number}

%p
  %b Claimed:
  %span{class: "label label-#{@room.set_claimed_label}"}
    = @room.claimed_status
%p
  %b Claimed by:
  = @room.claimed_by
%p
  %b Number of users checked in:
  = @room.users.size

%p
  %b Hash
  = @room.id_hash

%p
  = image_tag get_image_path(@room), width: '40%'


= link_to 'Edit', edit_room_path(@room), class: 'btn btn-warning'
= link_to 'Back', rooms_path, class: 'btn btn-inverse'